version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - cache:/data
  api:
    build: .
    restart: always
    ports:
      - '8000:80'
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/code
volumes:
  cache: